name: Test Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
        pip install -e .

    - name: Test import
      run: |
        python -c "from saf import data, dynamic_quant, utils"
